dbs:
  # Head to your `Article` database and copy/paste the URL here (or just the
  #   part following your workspace name)
  articles: Readings
  # Head to your `Author` database and copy/paste the URL here (or just the part
  #   following your workspace name)
  authors: Authors


status:
  # Set this to whatever prefix you'd like to designate status. OR you may leave
  #   it blank.
  prefix: "status:"
  # Create as many states as you would like. Provide a valid Notion color, or
  #   leave it as "default"
  states:
    unread: { name: "To Read", color: "red", }
    read: { name: "Done", color: "green", }

fields-methods:
  # State how we should split labels to extract `field-method` pairs. TAKE CARE
  #   TO ENSURE THIS ONLY APPEARS ONCE PER LABEL.
  delim: " - "
  fields:
    # Fields should look like this:
    # <abbr>: { color: <color>, name: <name> }
  methods:
    # Methods should look like this:
    # <abbr>: { color: <color>, name: <name> }
