name: "Sync Paperpile to Notion"

on:
  push:
    paths:
      - "**.bib"

jobs:
  sync-to-notion:
    name: "Sync Paperpile to Notion"
    runs-on: "ubuntu-latest"
    concurrency: 
      group: "paperpile-sync"
      cancel-in-progress: true
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Begin Paperpile Sync"
        uses: "jmuchovej/paperpile-notion@latest"
        with:
          # You can change this to whatever filename you desire
          references: "references.bib"
          token: "${{ secrets.NOTION_INTEGRATION_TOKEN }}"
