name: "Sync Paperpile to Notion"

on:
  push:
    paths:
      - "**.bib"

jobs:
  sync-to-notion:
    name: "Sync Paperpile to Notion"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jmuchovej/paperpile-notion@0.3.5
        with:
          references: references.bib
          token: ${{ secrets.NOTION_INTEGRATION_TOKEN }}
